# Generated by Django 4.2.16 on 2024-10-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='categoryincomes',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
    ]
