# Generated by Django 4.2.16 on 2024-10-23 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_name_alter_categoryincomes_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyincoms',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dailyincoms',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyExpenses',
        ),
        migrations.DeleteModel(
            name='DailyIncoms',
        ),
    ]
