# Generated by Django 4.2.16 on 2024-10-02 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_categoryincomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.PositiveIntegerField(blank=True, null=True, verbose_name='Доходы')),
                ('extra_income', models.PositiveIntegerField(blank=True, null=True, verbose_name='Доп доходы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
