# Generated by Django 4.2.16 on 2024-10-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_financialstatement_expenses_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='expenses_live',
            field=models.PositiveIntegerField(default=0, verbose_name='Расход текущий'),
        ),
    ]
