# Generated by Django 4.2.16 on 2024-10-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_dailyexpenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexpenses',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='КАТЕГОРИЯ'),
        ),
    ]
