# Generated by Django 4.2.16 on 2024-10-04 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_dailyexpenses_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyexpenses',
            options={'verbose_name': 'Расход за день', 'verbose_name_plural': 'Расходы за день'},
        ),
        migrations.AlterModelOptions(
            name='dailyincoms',
            options={'verbose_name': 'Доход за день', 'verbose_name_plural': 'Доходы за день'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Доход за месяц', 'verbose_name_plural': 'Доходы за месяц'},
        ),
        migrations.AlterModelOptions(
            name='necessaryexpenses',
            options={'verbose_name': 'Расход за месяц', 'verbose_name_plural': 'Расходы за месяц'},
        ),
        migrations.RemoveField(
            model_name='income',
            name='extra_income',
        ),
        migrations.RemoveField(
            model_name='income',
            name='income',
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.categoryincomes', verbose_name='КАТЕГОРИЯ'),
        ),
        migrations.AddField(
            model_name='income',
            name='sum',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='СУММА'),
        ),
        migrations.AddField(
            model_name='income',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='ДАТА СОЗДАНИЯ'),
        ),
        migrations.AddField(
            model_name='income',
            name='time_upate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='ДАТА ОБНОВЛЕНИЯ'),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='ОПИСАНИЕ'),
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
