# Generated by Django 4.2.16 on 2024-10-09 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_dailyexpenses_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='necessaryexpenses',
            old_name='time_upate',
            new_name='time_update',
        ),
        migrations.AlterField(
            model_name='dailyexpenses',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='КАТЕГОРИЯ'),
        ),
        migrations.AlterField(
            model_name='dailyincoms',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.categoryincomes', verbose_name='КАТЕГОРИЯ'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.categoryincomes', verbose_name='КАТЕГОРИЯ'),
        ),
        migrations.AlterField(
            model_name='necessaryexpenses',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='КАТЕГОРИЯ'),
        ),
        migrations.CreateModel(
            name='UserCategoryIncomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательская категория доходов',
                'verbose_name_plural': 'Пользовательские категории доходов',
            },
        ),
        migrations.CreateModel(
            name='UserCategoryExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательская категория расхода',
                'verbose_name_plural': 'Пользовательские категории расходов',
            },
        ),
    ]
